myblog/blog/urls.py
from django.urls import path
from . import views

urlpatterns = [path('', views.PostView.as_view()),
               path('<int:pk>/', views.PostDetail.as_view()),
               path('review/<int:pk>/', views.AddComments.as_view(), name='add_comments'),
               path('<int:pk>/add_likes/', views.AddLike.as_view(), name='add_likes'),
               path('<int:pk>/del_likes/', views.DelLike.as_view(), name='del_likes')]

myblog/myblog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



myblog/blog/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class Post(models.Model):
    '''Данные о посте'''
    title = models.CharField('Заголовок записи', max_length=100)
    description = models.TextField('Текст записи')
    author = models.CharField('Имя автора', max_length=100)
    date = models.DateField('Дата публикации')
    img = models.ImageField('Изображение', upload_to='image/%Y')

    def __str__(self):
        return f'{self.title}, {self.author}'

    class Meta:
        verbose_name = 'Запись'
        verbose_name_plural = 'Записи'


class Comments(models.Model):
    '''Комментарий'''
    email = models.EmailField()
    name = models.CharField('Имя', max_length=50)
    text_comments = models.TextField('Текст комментария', max_length=2000)
    date = models.DateTimeField('Дата комментария', default=timezone.now, null=True, blank=True)
    post = models.ForeignKey(Post, verbose_name='Публикация', on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.name}, {self.post}'

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'


class Likes(models.Model):
    '''Лайки'''
    ip = models.CharField('IP-адрес', max_length=100)
    pos = models.ForeignKey(Post, verbose_name='Публикация', on_delete=models.CASCADE)

myblog/blog/views.py
from django.shortcuts import render, redirect
from django.template.context_processors import request
from django.template.defaulttags import comment
from django.views.generic import View
from .models import Post, Likes
from .form import CommentsForm

# Create your views here.
class PostView(View):
    '''Вывод записей'''
    def get(self, request):
        posts = Post.objects.all()
        return render(request, 'blog/blog.html', {'post_list': posts})


class PostDetail(View):
    ''' Отдельная страница записи '''
    def get(self, request, pk):
        post = Post.objects.get(id=pk)
        form = CommentsForm()
        return render(request, 'blog/blog_detail.html', {'post': post, 'form': form})


class AddComments(View):
    '''Добавление комментариев'''
    def post(self, request, pk):
        form = CommentsForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post_id = pk
            comment.save()
        return redirect(f'/{pk}')


def get_client_ip(request):
    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forwarded_for:
        ip = x_forwarded_for.split(',')[0]
    else:
        ip = request.META.get('REMOTE_ADDR')
    return ip


class AddLike(View):
    '''Добавление лайка'''
    def get(self, request, pk):
        ip_client = get_client_ip(request)
        try:
            Likes.objects.get(ip=ip_client, pos_id=pk)
            return redirect(f'/{pk}')
        except:
            new_like = Likes()
            new_like.ip = ip_client
            new_like.pos_id = int(pk)
            new_like.save()
            return redirect(f'/{pk}')

class DelLike(View):
    '''Удаление лайка/дизлайк'''
    def get(self, request, pk):
        ip_client = get_client_ip(request)
        try:
            like = Likes.objects.get(ip=ip_client)
            like.delete()
            return redirect(f'/{pk}')
        except:
            return redirect(f'/{pk}')

myblog/templates/blog/blog.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <title>MiniBlog - Django</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css" media="all" />
    <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}" />
</head>
<body>
<div class="shell">
    <div class="border">
        <div id="navigation">
            <ul>
                <li><a href="/" class="active">Главная</a></li>
                <li><a href="/admin">Админ панель</a></li>
            </ul>
        </div>

        <div id="main">
            <div id="content" class="left">
                <div class="projects">
                    <h3>Последние записи</h3>
                    {% for post in post_list %}
                    <div class="item">
                        <div class="image left">
                            <a href="{{ post.id }}">
                                <img src="{{ post.img.url }}" alt="{{ post.title }}" />
                            </a>
                        </div>
                        <div class="text left">
                            <h4><a href="{{ post.id }}">{{ post.title }}</a></h4>
                            <p>{{ post.description }}</p>
                            <p class="post-meta">
                                <span class="author">Автор: {{ post.author }}</span>
                                <span class="likes">❤ {{ post.likes_set.all.count }}</span>
                                <span class="comments">💬 {{ post.comments_set.all.count }}</span>
                            </p>
                        </div>
                        <div class="cl">&nbsp;</div>
                    </div>
                    {% empty %}
                    <div class="no-posts">
                        <p>Нет доступных записей.</p>
                    </div>
                    {% endfor %}
                </div>
            </div>
            
            <div class="cl">&nbsp;</div>
        </div>
    </div>
    
    <div id="footer">
        <p class="copy right">Copyright &copy; {% now "Y" %} MiniBlog-Django</p>
    </div>
</div>
</body>
</html>

myblog/templates/blog/blog_detail.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <title>{{ post.title }} | MiniBlog</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css" media="all" />
    <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}" />
</head>
<body>
<div class="shell">
    <div class="border">
        <div id="navigation">
            <ul>
                <li><a href="/">Главная</a></li>
                <li><a href="/admin">Админ панель</a></li>
            </ul>
        </div>

        <div id="main">
            <div id="content" class="left">
                <div class="projects">
                    <h3>{{ post.title }}</h3>
                    <div class="post-image">
                        <img src="{{ post.img.url }}" alt="{{ post.title }}" style="max-width: 100%; border-radius: 8px; margin: 20px 0;"/>
                    </div>
                    <div class="item">
                        <div class="text">
                            <p>{{ post.description }}</p>
                            <p class="post-meta">
                                <span class="author">Автор: {{ post.author }}</span>
                                <span class="date">Опубликовано: {{ post.date|date:"d.m.Y" }}</span>
                            </p>
                        </div>
                        <div class="cl">&nbsp;</div>
                    </div>
                </div>
            </div>
            
            <div class="likes-section">
                <div class="likes-count">
                    <p>Понравилось: {{ post.likes_set.all.count }}</p>
                </div>
                <div class="like-buttons">
                    <a href="{% url 'add_likes' post.id %}" class="like-btn">👍 Нравится</a>
                    <a href="{% url 'del_likes' post.id %}" class="dislike-btn">👎 Не нравится</a>
                </div>
            </div>
            
            <div class="comments-section">
                <h3>Комментарии ({{ post.comments_set.all.count }})</h3>
                {% for comment in post.comments_set.all %}
                <div class="view_comment">
                    <h4>{{ comment.name }}</h4>
                    <p>{{ comment.text_comments }}</p>
                    <small class="comment-date">{{ comment.date|date:"d.m.Y H:i" }}</small>
                </div>
                {% empty %}
                <p>Пока нет комментариев. Будьте первым!</p>
                {% endfor %}
            </div>

            <div class="form-comment">
                <h3>Оставить комментарий</h3>
                <div>
                    <form action="{% url 'add_comments' post.id %}" method="post">
                        {% csrf_token %}
                        <div>
                            <label>Ваш комментарий</label>
                            {{ form.text_comments }}
                        </div>
                        <div>
                            <label>Ваше имя *</label>
                            {{ form.name }}
                        </div>
                        <div>
                            <label>Ваш Email *</label>
                            {{ form.email }}
                        </div>
                        <div>
                            <input type="submit" value="Отправить комментарий">
                        </div>
                    </form>
                </div>
            </div>

            <div class="cl">&nbsp;</div>
        </div>
    </div>
    
    <div id="footer">
        <p class="copy right">Copyright &copy; {% now "Y" %} MiniBlog-Django</p>
    </div>
</div>
</body>
</html>